// Header/Footer 文案：逐字取自原 Astro 站 website/src/i18n/en.ts 与 zh.ts 的 nav / footer / locale 段。
export const navContent = {
    en: {
        nav: {
            cases: 'Customer Cases',
            freeEnterpriseLicense: 'Free Enterprise License',
            pricing: 'Pricing',
            changelog: 'Changelog',
            blog: 'Blog',
            docs: 'Docs',
            license: 'Account',
            signIn: 'Sign in',
        },
        footer: {
            tagline: 'Unified remote access, access control, and operations auditing',
            docs: 'Docs',
            github: 'GitHub',
            pricing: 'Pricing',
            cases: 'Customer Cases',
            license: 'License Portal',
            terms: 'Terms of Service',
            privacy: 'Privacy Policy',
            termark: 'Termark SSH Client',
            copyright: 'Copyright © 2026 Pointer Drift Technology Studio',
        },
        locale: {
            htmlLang: 'en',
            hreflang: 'en',
            switchLabel: '切换到中文',
            switchText: '中文',
            openMenu: 'Open navigation',
            primaryNav: 'Main navigation',
        },
    },
    zh: {
        nav: {
            cases: '客户案例',
            freeEnterpriseLicense: '免费企业版授权',
            pricing: '价格',
            changelog: '更新日志',
            blog: '博客',
            docs: '文档',
            license: '账户',
            signIn: '登录',
        },
        footer: {
            tagline: '统一远程访问、权限控制与运维审计',
            docs: '文档',
            github: 'GitHub',
            pricing: '价格',
            cases: '客户案例',
            license: '授权系统',
            terms: '服务条款',
            privacy: '隐私政策',
            termark: 'Termark SSH 客户端',
            copyright: '© 2026 指针漂移科技工作室',
        },
        locale: {
            htmlLang: 'zh-CN',
            hreflang: 'zh-CN',
            switchLabel: 'Switch to English',
            switchText: 'EN',
            openMenu: '打开导航',
            primaryNav: '主导航',
        },
    },
};
